version: 2
updates:

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  ignore:
    # Only send PRs for patch versions of Python.
    - dependency-name: "python"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

