[tool.pytest.ini_options]
addopts = "-q"
filterwarnings = [
    "error", # Fail the tests if there are any warnings.

    # Required until marshmallow 3.15.0 is released which should fix this. See:
    # * https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst
    # * https://github.com/marshmallow-code/marshmallow/pull/1903
    "ignore:^distutils Version classes are deprecated\\. Use packaging.version instead\\.$:DeprecationWarning:marshmallow:17",

    # pkg_resources is calling its own deprecated function? Anyway I don't think the problem is with us.
    "ignore:^Deprecated call to .pkg_resources\\.declare_namespace\\('.*'\\).\\.:DeprecationWarning:pkg_resources",

    # pkg_resources used in some of our dependencies
    "ignore:^pkg_resources is deprecated as an API$:DeprecationWarning:pkg_resources",
    "ignore:^pkg_resources is deprecated as an API:DeprecationWarning:pyramid",

    # https://github.com/webpy/webpy/issues/732
    "ignore:^'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning:webob",
]
