name: Continuous integration
on: pull_request
jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5-alpine
        ports:
          - 5434:5432
    env:
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install tox
      run: python -m pip install tox
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Create test databases
      run: |
        psql -U postgres -h localhost -p 5434 -c 'CREATE DATABASE checkmate_test'
        psql -U postgres -h localhost -p 5434 -c 'CREATE DATABASE checkmate_functests'
    - name: Cache the .tox dir
      uses: actions/cache@v2
      with:
        path: .tox
        key: ${{ runner.os }}-tox-${{ secrets.CACHE_VERSION }}-${{ hashFiles('tox.ini', 'requirements*', 'setup.py', 'setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-tox-${{ secrets.CACHE_VERSION }}-
    - name: Run tox
      run: tox --parallel auto -e lint,checkformatting,tests,functests
