# Perform initial stages of a Checkmate release.
#
# Once this is complete the prod_release workflow needs to be run to 
# update production.
name: initial-deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  qa:
    needs: create-image
    name: ${{ github.event.repository.name }}
    uses: hypothesis/workflows/.github/workflows/eb-update.yml@main
    with:
      Application: ${{ github.event.repository.name }}
      Environment: qa
      Region: us-west-1
      Operation: deploy
      Version: latest
    secrets: inherit
