name: Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      staging:
        type: boolean
        description: Redeploy Staging
      production:
        type: boolean
        description: Redeploy Production
jobs:
  staging:
    name: Staging
    if: inputs.staging
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Staging
      github_environment_url: https://checkmate.staging.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: checkmate
      elasticbeanstalk_environment: staging
    secrets: inherit
  production:
    name: Production
    if: inputs.production
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: redeploy
      github_environment_name: Production
      github_environment_url: https://checkmate.hypothes.is/
      aws_region: us-west-1
      elasticbeanstalk_application: checkmate
      elasticbeanstalk_environment: prod
    secrets: inherit
